// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package publicconcil

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Publicconcil() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"public-council\" class=\"section public-council-section\"><div class=\"container\"><div class=\"section-title animate-on-scroll\"><h2>Обществен съвет</h2><p>Гражданско участие в образователния процес</p></div><div class=\"row justify-content-center\"><div class=\"col-lg-8\"><div class=\"council-info-card animate-on-scroll\"><div class=\"council-icon\"><i class=\"fas fa-users\"></i></div><h3>Общественият съвет към НТГ</h3><p>Общественият съвет е орган за гражданско участие и обществен контрол, който се състои от представители на родителите, местната общност, синдикати, работодателски организации и неправителствени организации.</p><div class=\"council-features\"><div class=\"row g-3\"><div class=\"col-md-6\"><div class=\"feature-item\"><i class=\"fas fa-check-circle text-danger me-2\"></i> <span>Общественен контрол</span></div></div><div class=\"col-md-6\"><div class=\"feature-item\"><i class=\"fas fa-check-circle text-danger me-2\"></i> <span>Съвети и препоръки</span></div></div><div class=\"col-md-6\"><div class=\"feature-item\"><i class=\"fas fa-check-circle text-danger me-2\"></i> <span>Подкрепа на инициативи</span></div></div><div class=\"col-md-6\"><div class=\"feature-item\"><i class=\"fas fa-check-circle text-danger me-2\"></i> <span>Връзка с общността</span></div></div></div></div><a href=\"/public-council\" class=\"btn btn-danger btn-lg mt-4\"><i class=\"fas fa-users me-2\"></i> Членове на обществения съвет</a></div></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
