// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package achievements

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Styles() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\n    .achievements-section {\n        background: var(--gradient-dark);\n        color: var(--white);\n    }\n\n    .achievements-section .section-title h2,\n    .achievements-section .section-title p {\n        color: var(--white);\n    }\n\n    .achievement-card {\n        text-align: center;\n        padding: 30px 20px;\n        background: rgba(255, 255, 255, 0.1);\n        border-radius: 15px;\n        backdrop-filter: blur(10px);\n        border: 1px solid rgba(255, 255, 255, 0.2);\n        height: 100%;\n        transition: transform 0.3s ease;\n    }\n\n    .achievement-card:hover {\n        transform: translateY(-10px);\n    }\n\n    .achievement-number {\n        font-size: 3rem;\n        font-weight: 700;\n        color: var(--white);\n        margin-bottom: 15px;\n        display: block;\n    }\n\n    .achievement-card h4 {\n        margin-bottom: 15px;\n        font-weight: 600;\n    }\n\n    .achievement-card p {\n        opacity: 0.8;\n    }\n</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
