// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package achievements

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Achievements() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"section achievements-section\"><div class=\"container\"><div class=\"section-title animate-on-scroll\"><h2>Нашите Постижения</h2><p>Резултати, с които се гордеем</p></div><div class=\"row g-4\"><div class=\"col-lg-3 col-md-6\"><div class=\"achievement-card animate-on-scroll\"><span class=\"achievement-number\">15000+</span><h4>Възпитаници</h4><p>Успешни възпитаници в различни сфери на обществото</p></div></div><div class=\"col-lg-3 col-md-6\"><div class=\"achievement-card animate-on-scroll delay-1\"><span class=\"achievement-number\">95%</span><h4>Прием във ВУЗ</h4><p>От нашите завършили продължават образованието си</p></div></div><div class=\"col-lg-3 col-md-6\"><div class=\"achievement-card animate-on-scroll delay-2\"><span class=\"achievement-number\">50+</span><h4>Награди</h4><p>Национални и международни отличия и награди</p></div></div><div class=\"col-lg-3 col-md-6\"><div class=\"achievement-card animate-on-scroll delay-3\"><span class=\"achievement-number\">25+</span><h4>Партньорства</h4><p>Активни партньорства с водещи университети и фирми</p></div></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
