// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package achievements

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Scripts() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script>\n    function animateCounters() {\n        const counters = document.querySelectorAll('.achievement-number');\n\n        counters.forEach(counter => {\n            const target = parseInt(counter.textContent.replace(/\\D/g, ''));\n            const duration = 2000;\n            const increment = target / (duration / 16);\n            let current = 0;\n\n            const timer = setInterval(() => {\n                current += increment;\n                if (current >= target) {\n                    current = target;\n                    clearInterval(timer);\n                }\n\n                if (counter.textContent.includes('%')) {\n                    counter.textContent = Math.floor(current) + '%';\n                } else if (counter.textContent.includes('+')) {\n                    counter.textContent = Math.floor(current).toLocaleString() + '+';\n                } else {\n                    counter.textContent = Math.floor(current).toLocaleString();\n                }\n            }, 16);\n        });\n    }\n\n    // Animate counters when achievements section comes into view\n    document.addEventListener('DOMContentLoaded', function () {\n        const achievementsSection = document.querySelector('.achievements-section');\n        const observer = new IntersectionObserver((entries) => {\n            entries.forEach(entry => {\n                if (entry.isIntersecting) {\n                    animateCounters();\n                    observer.unobserve(entry.target);\n                }\n            });\n        }, { threshold: 0.5 });\n\n        if (achievementsSection) {\n            observer.observe(achievementsSection);\n        }\n    });\n\n</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
