// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package history

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Styles() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\n    .history-section {\n        background: var(--light-color);\n    }\n\n    .timeline {\n        position: relative;\n        padding: 0;\n        list-style: none;\n    }\n\n    .timeline::before {\n        content: '';\n        position: absolute;\n        top: 0;\n        bottom: 0;\n        left: 50%;\n        width: 4px;\n        background: var(--gradient-primary);\n        transform: translateX(-50%);\n    }\n\n    .timeline-item {\n        position: relative;\n        margin-bottom: 50px;\n    }\n\n    .timeline-item:nth-child(odd) .timeline-content {\n        margin-right: calc(50% + 40px);\n        text-align: right;\n    }\n\n    .timeline-item:nth-child(even) .timeline-content {\n        margin-left: calc(50% + 40px);\n        text-align: left;\n    }\n\n    .timeline-content {\n        background: var(--white);\n        padding: 30px;\n        border-radius: 10px;\n        box-shadow: 0 5px 20px rgba(0, 0, 0, 0.1);\n        position: relative;\n    }\n\n    .timeline-year {\n        position: absolute;\n        left: 50%;\n        transform: translateX(-50%);\n        background: var(--primary-color);\n        color: var(--white);\n        padding: 10px 20px;\n        border-radius: 25px;\n        font-weight: 700;\n        font-size: 1.1rem;\n        z-index: 10;\n    }\n\n    .timeline-content h4 {\n        color: var(--primary-color);\n        margin-bottom: 15px;\n        font-weight: 600;\n    }\n</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
