// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package history

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func History() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"history\" class=\"section history-section\"><div class=\"container\"><div class=\"section-title animate-on-scroll\"><h2>Нашата История</h2><p>Над век традиции в българското образование</p></div><div class=\"timeline\"><div class=\"timeline-item animate-on-scroll\"><div class=\"timeline-year\">1910</div><div class=\"timeline-content\"><h4>Основаване на училището</h4><p>Националната търговска гимназия е основана през 1910 година като първото специализирано училище за търговско образование в България.</p></div></div><div class=\"timeline-item animate-on-scroll delay-1\"><div class=\"timeline-year\">1945</div><div class=\"timeline-content\"><h4>Модернизация и развитие</h4><p>След Втората световна война училището преминава през период на модернизация и разширяване на учебните програми.</p></div></div><div class=\"timeline-item animate-on-scroll delay-2\"><div class=\"timeline-year\">1989</div><div class=\"timeline-content\"><h4>Нова ера на образованието</h4><p>С демократичните промени училището въвежда нови методи на обучение и разширява международните си контакти.</p></div></div><div class=\"timeline-item animate-on-scroll delay-3\"><div class=\"timeline-year\">2010</div><div class=\"timeline-content\"><h4>Столетен юбилей</h4><p>Празнуваме 100 години образователна традиция и въвеждаме най-съвременните технологии в обучението.</p></div></div><div class=\"timeline-item animate-on-scroll\"><div class=\"timeline-year\">2025</div><div class=\"timeline-content\"><h4>Бъдещето започва днес</h4><p>Продължаваме да бъдем лидери в образованието с иновативни програми и дигитална трансформация.</p></div></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
