// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package values

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Values() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"values\" class=\"section values-section\"><div class=\"container\"><div class=\"section-title animate-on-scroll\"><h2>Нашите Ценности</h2><p>Принципите, които ни ръководят всеки ден</p></div><div class=\"row g-4\"><div class=\"col-lg-3 col-md-6\"><div class=\"value-card animate-on-scroll\"><div class=\"icon\"><i class=\"fas fa-graduation-cap\"></i></div><h4>Качество</h4><p>Стремим се към най-високите стандарти в образованието и постоянно подобряваме нашите методи.</p></div></div><div class=\"col-lg-3 col-md-6\"><div class=\"value-card animate-on-scroll delay-1\"><div class=\"icon\"><i class=\"fas fa-lightbulb\"></i></div><h4>Иновации</h4><p>Въвеждаме най-съвременните технологии и методи за ефективно и интересно обучение.</p></div></div><div class=\"col-lg-3 col-md-6\"><div class=\"value-card animate-on-scroll delay-2\"><div class=\"icon\"><i class=\"fas fa-handshake\"></i></div><h4>Етика</h4><p>Възпитаваме учениците си в дух на честност, отговорност и зачитане на другите.</p></div></div><div class=\"col-lg-3 col-md-6\"><div class=\"value-card animate-on-scroll delay-3\"><div class=\"icon\"><i class=\"fas fa-users\"></i></div><h4>Общност</h4><p>Създаваме среда на взаимопомощ и сътрудничество между ученици, учители и родители.</p></div></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
