// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package schoolboard

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Styles() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\n    .school-board-section {\n        background: var(--light-color);\n    }\n\n    .board-info-card {\n        background: var(--white);\n        padding: 50px;\n        border-radius: 20px;\n        text-align: center;\n        position: relative;\n        overflow: hidden;\n        box-shadow: 0 5px 20px rgba(0, 0, 0, 0.1);\n    }\n\n    .board-info-card::before {\n        content: '';\n        position: absolute;\n        top: 0;\n        left: 0;\n        right: 0;\n        height: 5px;\n        background: var(--gradient-primary);\n    }\n\n    .board-icon {\n        font-size: 4rem;\n        color: var(--primary-color);\n        margin-bottom: 30px;\n    }\n\n    .board-info-card h3 {\n        color: var(--dark-color);\n        margin-bottom: 25px;\n        font-weight: 600;\n    }\n\n    .board-features {\n        margin: 30px 0;\n    }\n</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
