// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package qualifications

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Scripts() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script>\n    document.addEventListener('DOMContentLoaded', function() {\n        // Animate progress bars when they come into view\n        const progressObserver = new IntersectionObserver((entries) => {\n            entries.forEach(entry => {\n                if (entry.isIntersecting) {\n                    const card = entry.target;\n                    card.classList.add('animate-progress');\n                    \n                    // Animate the progress bars inside this card\n                    const progressBars = card.querySelectorAll('.progress-bar');\n                    progressBars.forEach((bar, index) => {\n                        setTimeout(() => {\n                            const percentage = bar.getAttribute('data-percentage');\n                            bar.style.width = percentage + '%';\n                        }, index * 200);\n                    });\n                    \n                    progressObserver.unobserve(card);\n                }\n            });\n        }, { threshold: 0.3 });\n\n        // Observe qualification category cards\n        document.querySelectorAll('.qualification-category-card').forEach(card => {\n            progressObserver.observe(card);\n        });\n    });\n</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
