// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package newssection

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/GeorgiChalakov01/ntg/backend/app/pages/home/components/newsitem"
)

func NewsSection() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"section news-section\"><div class=\"container\"><div class=\"section-title animate-on-scroll\"><h2>Последни Новини</h2><p>Бъдете в крак с последните събития в НТГ</p><a href=\"#\" class=\"view-all\">Виж всички новини <i class=\"fas fa-arrow-right\"></i></a></div><div class=\"row g-4\"><div class=\"col-lg-3 col-md-6\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = newsitem.NewsItem(
			"Старт на новата учебна година",
			"15 Септември 2025",
			"https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.snexplores.org%2Fwp-content%2Fuploads%2F2023%2F01%2F1440_LL_school-start-times_feat.jpg&f=1&nofb=1&ipt=44bf5b39c00490e65982eee06fe16bfbcb528a1dbbd0b8d6b9971ce47939bb22",
			"Учениците от НТГ посрещнаха новата учебна година с тържествена церемония.",
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><div class=\"col-lg-3 col-md-6\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = newsitem.NewsItem(
			"Студентски бизнес форум 2023",
			"10 Септември 2023",
			"https://images.unsplash.com/photo-1523240795612-9a054b0db644?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
			"Нашите ученици представиха иновативни бизнес идеи пред експерти.",
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><div class=\"col-lg-3 col-md-6\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = newsitem.NewsItem(
			"Спортни успехи",
			"5 Септември 2023",
			"https://images.unsplash.com/photo-1523580494863-6f3031224c94?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
			"Нашите баскетболисти спечелиха регионалното първенство.",
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><div class=\"col-lg-3 col-md-6\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = newsitem.NewsItem(
			"Партньорство с водещи фирми",
			"1 Септември 2023",
			"https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.novum.no%2Frails%2Factive_storage%2Fblobs%2FeyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFlDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a2d48cd6345f850d97017516fb5176f23af71668%2Fcompany.jpg&f=1&nofb=1&ipt=add5580beb50edf426f9762fd0732abc757c30ae87b03062d95acfcd81fd5ff0",
			"Подписахме споразумение за сътрудничество с глобална компания.",
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
